
default: &default
  encoding: unicode


development:
  <<: *default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: shit_production
  host: localhost
  username: rails
  password: <%= ENV['POSTGRES_SUCKS_DATABASE_PASSWORD'] %>
